### ISSUE TITLE
Gulp Browserify Fails

### ISSUE THREAD

**Issue by ianrtracey** [ryanlanciaux/griddle-gulp-test#2]
After running npm install and gulp, the gulp stream fails with the following error:

`events.js:85
      throw er; // Unhandled 'error' event
            ^
ReactifyError: /Users/iantracey/Dropbox/code/latitude/scribe/scripts/components/fake_a421934a.js: Parse Error: Line 1: Unexpected token (
    at throwError (/Users/iantracey/Dropbox/code/latitude/scribe/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2644:21)
    at throwUnexpected (/Users/iantracey/Dropbox/code/latitude/scribe/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2706:9)
    at consumeSemicolon (/Users/iantracey/Dropbox/code/latitude/scribe/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2829:13)
    at parseVariableStatement (/Users/iantracey/Dropbox/code/latitude/scribe/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:4600:9)
    at parseStatement (/Users/iantracey/Dropbox/code/latitude/scribe/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5402:24)
    at parseSourceElement (/Users/iantracey/Dropbox/code/latitude/scribe/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6139:24)
    at parseProgramElement (/Users/iantracey/Dropbox/code/latitude/scribe/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6185:16)
    at parseProgramElements (/Users/iantracey/Dropbox/code/latitude/scribe/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6217:29)
    at parseProgram (/Users/iantracey/Dropbox/code/latitude/scribe/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:6230:16)
    at Object.parse (/Users/iantracey/Dropbox/code/latitude/scribe/node_modules/reactify/node_modules/jstransform/node_modules/esprima-fb/esprima.js:7566:23)`

**Comment by ianrtracey** [comment]
Fixed it by changing my own source.

**Comment by ryanlanciaux** [comment]
Ahh okay cool - please let me know if there's anything I should change in this repo. I haven't been keeping this up-to-date so much so any thoughts around that would be appreciated.
